/**
  ******************************************************************************
  * @file    app_bluenrg_ms.c
  * @brief   BlueNRG-MS init + main-loop callback for Intelligent-home.
  *
  *          NOTE: this file was originally generated by CubeMX from the
  *          X-CUBE-BLE1 "SensorDemoBLESensor" application template, and has
  *          since been substantially rewritten. Regenerating with the same
  *          template will REVERT the body — before regenerating, switch the
  *          BLE application in CubeMX to "Custom Template", or commit the
  *          current state to git first.
  *          See .claude/rules/file-modification-scope.md
  ******************************************************************************
  */

/* Includes ------------------------------------------------------------------*/
#include "app_bluenrg_ms.h"

#include <stdio.h>

#include "hci.h"
#include "hci_le.h"
#include "hci_tl.h"
#include "link_layer.h"

#include "sensor.h"
#include "gatt_db.h"

#include "compiler.h"
#include "bluenrg_utils.h"
#include "b_l475e_iot01a1.h"
#include "bluenrg_gap.h"
#include "bluenrg_gap_aci.h"
#include "bluenrg_gatt_aci.h"
#include "bluenrg_hal_aci.h"

/* USER CODE BEGIN Includes */

/* USER CODE END Includes */

/* Private defines -----------------------------------------------------------*/

/* Private macros ------------------------------------------------------------*/

/* Private variables ---------------------------------------------------------*/
extern volatile uint8_t set_connectable;   /* defined in sensor.c */

/* Referenced from sensor.c and gatt_db.c. */
uint8_t bnrg_expansion_board = IDB04A1;    /* upgraded to IDB05A1 at runtime */
uint8_t bdaddr[BDADDR_SIZE];

/* USER CODE BEGIN PV */

/* USER CODE END PV */

/* Private function prototypes -----------------------------------------------*/
static void User_Init(void);
static void User_Process(void);

/* USER CODE BEGIN PFP */

/* USER CODE END PFP */

void MX_BlueNRG_MS_Init(void)
{
  /* USER CODE BEGIN SV */

  /* USER CODE END SV */

  /* USER CODE BEGIN BlueNRG_MS_Init_PreTreatment */

  /* USER CODE END BlueNRG_MS_Init_PreTreatment */

  uint16_t service_handle;
  uint16_t dev_name_char_handle;
  uint16_t appearance_char_handle;
  uint8_t  bdaddr_len_out;
  uint8_t  hwVersion;
  uint16_t fwVersion;
  int      ret;

  User_Init();

  hci_init(user_notify, NULL);

  getBlueNRGVersion(&hwVersion, &fwVersion);

  /* aci_hal_write_config_data() must be the first command after reset, so
   * issue a fresh reset here in case it is ever needed. */
  hci_reset();
  HAL_Delay(100);

  PRINTF("HWver %d, FWver %d\r\n", hwVersion, fwVersion);
  if (hwVersion > 0x30) {  /* X-NUCLEO-IDB05A1 / IDB05A2 */
    bnrg_expansion_board = IDB05A1;
  }

  ret = aci_hal_read_config_data(CONFIG_DATA_RANDOM_ADDRESS, BDADDR_SIZE,
                                 &bdaddr_len_out, bdaddr);
  if (ret) {
    PRINTF("Read static random address failed.\r\n");
  }
  if ((bdaddr[5] & 0xC0) != 0xC0) {
    PRINTF("Static random address not well formed.\r\n");
    while (1);
  }

  ret = aci_gatt_init();
  if (ret) PRINTF("aci_gatt_init failed.\r\n");

  if (bnrg_expansion_board == IDB05A1) {
    ret = aci_gap_init_IDB05A1(GAP_PERIPHERAL_ROLE_IDB05A1, 0, 0x0A,
                               &service_handle, &dev_name_char_handle,
                               &appearance_char_handle);
  } else {
    ret = aci_gap_init_IDB04A1(GAP_PERIPHERAL_ROLE_IDB04A1,
                               &service_handle, &dev_name_char_handle,
                               &appearance_char_handle);
  }
  if (ret != BLE_STATUS_SUCCESS) PRINTF("aci_gap_init failed.\r\n");
  else
  /* Mirror the advertised local name into the standard GAP Device Name char. */
  {
    char dev_name[10];
    int  dn = snprintf(dev_name, sizeof(dev_name),
                       "HOME-%02X%02X", bdaddr[1], bdaddr[0]);
    ret = aci_gatt_update_char_value(service_handle, dev_name_char_handle, 0,
                                     dn, (uint8_t *)dev_name);
    if (ret) PRINTF("Device name update failed: 0x%02x\r\n", ret);
  }

  /* Open BLE — no pairing / encryption for v1 (docs §13). */

  PRINTF("BLE stack initialised.\r\n");

  ret = Add_HomeSensor_Service();
  if (ret == BLE_STATUS_SUCCESS) {
    PRINTF("Home Sensor Service added.\r\n");
  } else {
    PRINTF("Add_HomeSensor_Service failed: 0x%02x\r\n", ret);
    while (1);
  }

  ret = Add_HomeControl_Service();
  if (ret == BLE_STATUS_SUCCESS) {
    PRINTF("Home Control Service added.\r\n");
  } else {
    PRINTF("Add_HomeControl_Service failed: 0x%02x\r\n", ret);
    while (1);
  }

  /* High-power profile, PA level 4 (~-2.1 dBm). */
  aci_hal_set_tx_power_level(1, 4);

  /* USER CODE BEGIN BlueNRG_MS_Init_PostTreatment */

  /* USER CODE END BlueNRG_MS_Init_PostTreatment */
}

/*
 * BlueNRG-MS background task — called from BleTask in freertos.c.
 */
void MX_BlueNRG_MS_Process(void)
{
  /* USER CODE BEGIN BlueNRG_MS_Process_PreTreatment */

  /* USER CODE END BlueNRG_MS_Process_PreTreatment */

  User_Process();
  hci_user_evt_proc();

  /* USER CODE BEGIN BlueNRG_MS_Process_PostTreatment */

  /* USER CODE END BlueNRG_MS_Process_PostTreatment */
}

static void User_Init(void)
{
  /* LED2 (PB14) is the BSP-owned BLE status LED. */
  BSP_LED_Init(LED2);
  /* COM1 = USART1 → ST-LINK VCP. PRINTF lands here. */
  BSP_COM_Init(COM1);
}

static void User_Process(void)
{
  if (set_connectable) {
    Set_DeviceConnectable();
    set_connectable = FALSE;
  }
}
